val track charge fix
Mu2e/Offline pull request #1255
Opened 2024-05-04 13:21 UTC by rlcee

I found that some validation jobs were ended with a "tried to save duplicate histogram" error, which I fixed with adding the "2".  Then I reran my test and it seg-faulted on this line
`double ksCharge = ks.intersections().front().pstate_.charge();`
I see that the intersections access is protected against empty vectors in the other access, and if an empty vector is possible here, then this line could cause undefined behavior and I got lucky.  So I moved it into the protected block.  But I also lazily switched to the charge of the sid surface intersection instead of the front of the intersections vector.  I suspect this is OK for this purpose (an more consistent?), but if the front of the vector is important, then I can re-write to get that safely.

2024-05-04 13:22 UTC, FNALbuild commented
Hi @rlcee,
You have proposed changes to files in these packages:
- Validation

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 90f7387abc836058d5fb1670a13e4cd669cc3f23: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2024-05-04 14:02 UTC, FNALbuild commented
:sunny: The build tests passed at 90f7387abc836058d5fb1670a13e4cd669cc3f23.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 90f7387abc836058d5fb1670a13e4cd669cc3f23 at 07a76f5fcecbc4e3ef9c6edf73c17dd777164d46 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/scons.log). Build time: 21 min 19 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :large_orange_diamond: | [TODO (1) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 239 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 90f7387abc836058d5fb1670a13e4cd669cc3f23 after being merged into the base branch at 07a76f5fcecbc4e3ef9c6edf73c17dd777164d46.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2086/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-05-04 21:33 UTC, kutschke approved these changes
This looks right to me.

I added Dave and Giani as reviewers as an FYI for them.  I plan to merge this evening so that the Sunday AM validation works.

2024-05-04 21:47 UTC, gianipez approved these changes
Eveything looks ok to me

2024-05-05 00:42 UTC, brownd1978 requested changes
I have provided an alternate, more robust and definitive fix in PR 1257.  Please use that instead.

2024-05-05 01:23 UTC, kutschke commented
This is superseded by PR #1257.  Closing it.

2024-05-05 01:23 UTC, closed without merging

2024-05-05 02:15 UTC, kutschke commented
> I have provided an alternate, more robust and definitive fix in PR 1258. Please use that instead.

Yes - I saw it.