lower default SimpleTimeCluster straw/panel count thresholds
Mu2e/Offline pull request #1275
Opened 2024-05-29 17:08 UTC by edcallaghan

This PR relaxes the occupancy thresholds to construct `TimeCluster`s in `SimpleTimeCluster`, which seeds straight-line cosmic reconstruction. Using "bare minimum" thresholds as implemented here (>= 1 panel, >= 2 straws), improves the efficiency for near-verticals from ~1% to ~10%. This is shown in the below plot, which can be cross-referenced against cosmic reco nightly validation.

[cosmics-all-tracks-counts-vs-costheta-log.pdf](https://github.com/Mu2e/Offline/files/15488167/cosmics-all-tracks-counts-vs-costheta-log.pdf)

2024-05-29 17:09 UTC, FNALbuild commented
Hi @edcallaghan,
You have proposed changes to files in these packages:
- CosmicReco

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for e86a4d8e3e9022dc85cb93e2f23226e0c626f6ab: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2024-05-29 17:36 UTC, FNALbuild commented
:sunny: The build tests passed at e86a4d8e3e9022dc85cb93e2f23226e0c626f6ab.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged e86a4d8e3e9022dc85cb93e2f23226e0c626f6ab at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/scons.log). Build time: 11 min 16 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 39 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at e86a4d8e3e9022dc85cb93e2f23226e0c626f6ab after being merged into the base branch at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2111/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-05-29 19:04 UTC, brownd1978 requested changes

2024-05-29 19:04 UTC, brownd1978 commented on CosmicReco/src/SimpleTimeCluster_module.cc
> +    fhicl::Atom<int> minnsh{Name("minNStrawHits"), Comment("minimum number of straw hits "), 2};
code defaults of algorithm parameters is deprecated.  Please remove this default and add the parameter to the prolog.  While you're in there, please do the same fo the other parameters.

2024-05-29 19:40 UTC, edcallaghan commented
@FNALbuild run build test

2024-05-29 19:40 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for c2fb3d946204839f6afc6bc4c484a6aa8ec6fac0: build  (Build queue is empty)

2024-05-29 20:22 UTC, FNALbuild commented
:umbrella: The build tests failed for c2fb3d946204839f6afc6bc4c484a6aa8ec6fac0.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged c2fb3d946204839f6afc6bc4c484a6aa8ec6fac0 at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/scons.log). Build time: 21 min 17 sec |
| ceSimReco | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/ceSimReco.log) Return Code 90. |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/g4study.log)  |
| cosmicSimReco | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/cosmicSimReco.log) Return Code 90. |
| cosmicOffSpill | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/cosmicOffSpill.log) Return Code 9. |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/ceSteps.log)  |
| ceDigi | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/ceDigi.log) Return Code 9. |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/muDauSteps.log)  |
| ceMix | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/ceMix.log) Return Code 9. |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 37 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at c2fb3d946204839f6afc6bc4c484a6aa8ec6fac0 after being merged into the base branch at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2112/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-05-29 22:39 UTC, edcallaghan commented
@FNALbuild run build test

2024-05-29 22:39 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 675286c197a8cb27c372bf98c96bdedd392331c0: build  (Build queue is empty)

2024-05-29 23:07 UTC, FNALbuild commented
:umbrella: The build tests failed for 675286c197a8cb27c372bf98c96bdedd392331c0.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 675286c197a8cb27c372bf98c96bdedd392331c0 at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/scons.log). Build time: 11 min 18 sec |
| ceSimReco | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/ceSimReco.log) Return Code 134. |
| g4test_03MT | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/g4test_03MT.log) Return Code 134. |
| transportOnly | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/transportOnly.log) Return Code 134. |
| POT | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/POT.log) Return Code 134. |
| g4study | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/g4study.log) Return Code 134. |
| cosmicSimReco | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/cosmicSimReco.log) Return Code 134. |
| cosmicOffSpill | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/cosmicOffSpill.log) Return Code 134. |
| ceSteps | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/ceSteps.log) Return Code 134. |
| ceDigi | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/ceDigi.log) Return Code 134. |
| muDauSteps | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/muDauSteps.log) Return Code 134. |
| ceMix | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/ceMix.log) Return Code 134. |
| rootOverlaps | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/rootOverlaps.log) Return Code 134. |
| g4surfaceCheck | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/g4surfaceCheck.log) Return Code 134. |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 37 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 675286c197a8cb27c372bf98c96bdedd392331c0 after being merged into the base branch at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2114/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-05-29 23:33 UTC, brownd1978 commented
There are errors in the new prolog causing the CI to fail.  In case you didn't know, you can't see the CI logs in a browser, but you can copy the links to them from GitHub and view them using 'curl' once logged on to a mu2egpvm* machine.

Failed to parse the configuration file 'Production/Validation/ceSimReco.fcl' with exception
---- Parse error BEGIN
  detected at or near line 44, character 19, of file "/scratch/workspace/GitHubPRTests/mu2e-offline-build-test/Offline/CosmicReco/fcl/prolog.fcl"
  included from line 15 of file "/scratch/workspace/GitHubPRTests/mu2e-offline-build-test/Production/JobConfig/reco/prolog.fcl"
  included from line 11 of file "./Production/Validation/ceSimReco.fcl"
  
      debugLevel : 0,
                    ^
---- Parse error END

2024-05-30 00:59 UTC, edcallaghan commented
@brownd1978 The prolog errors were the first failure, which I pushed a fix for. The latest jobs all failed non-gracefully with an underlying system error. For the art jobs, this presents as `*** Error in `mu2e': double free or corruption (!prev): 0x0000000005283d80 ***`, after the modules all run to completion.

It looks like there is an alternate `SimpleTimeCluster` defined in `mu2e_trig_config`, which will need to either inherit from here or have its configuration updated to accommodate the default values before some of the validaiton jobs here will succeed. But I don't think that that's behind the current slew of errors.

2024-05-30 01:12 UTC, edcallaghan commented
And, FWIW, after fixing that alternate `SimpleTimeCluster` configuration, the jobs (e.g. `ceSteps` and `ceDigi`) run fine locally. I'm going to trigger the tests again just to see what happens...

2024-05-30 01:13 UTC, edcallaghan commented
@FNALbuild run build test

2024-05-30 01:13 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 675286c197a8cb27c372bf98c96bdedd392331c0: build  (Build queue has 1 jobs)

2024-05-30 01:40 UTC, FNALbuild commented
:umbrella: The build tests failed for 675286c197a8cb27c372bf98c96bdedd392331c0.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 675286c197a8cb27c372bf98c96bdedd392331c0 at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/scons.log). Build time: 11 min 00 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/cosmicOffSpill.log) Return Code 9. |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/ceSteps.log)  |
| ceDigi | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/ceDigi.log) Return Code 9. |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/muDauSteps.log)  |
| ceMix | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/ceMix.log) Return Code 9. |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 37 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 675286c197a8cb27c372bf98c96bdedd392331c0 after being merged into the base branch at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2115/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-05-30 01:43 UTC, edcallaghan commented
Ok, not sure what went wrong with the last batch. But the three failing jobs are dependent on `mu2e_trig_config`. I'll submit a PR there to update the upstream configuration.

2024-05-30 02:36 UTC, kutschke commented
Ed has PR #28 in to mu2e_trig_config.  I would like him to change something in it but it should fix the problems as is.

I forget if we updated the CI to use mu2e_trig_config in test with. Let's see.

@FNALbuild run build test with Mu2e/mu2e_trig_config#28

2024-05-30 02:37 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 675286c197a8cb27c372bf98c96bdedd392331c0: build  (Build queue is empty)

2024-05-30 03:00 UTC, kutschke commented
You may already know this but just to be sure.   To test interactively, make sure you have all of Offline, Production and mu2e_trig_config in your muse working area ( if not, log out, clone the missing repos, login, mu2einit, muse setup and build ).  Then you can test the first one interactively with :

`
 mu2e -c Production/Validation/cosmicOffSpill.fcl -n 10`

The next one is a bit trickier since it uses the output of ceSteps and looks for it locally

```
 mu2e -c Production/Validation/ceSteps.fcl -n 10
 mu2e -c Production/Validation/ceDigi.fcl -n 10
```

The same for testing ceMix, it consumes the output of muDauSteps, which does not write output for event event.  So need to run enough to be sure.

'''
 mu2e -c Production/Validation/muDauSteps.fcl -n 100
  mu2e -c Production/Validation/ceMix.fcl -n 1
'''

Be sure to clean up the .art files in your working area when you are done.

If you get errors with text "root://fndcadoor.fnal. .... " you need a certiifcate to access files via xrootd.  Use "vomsCert".  See https://mu2ewiki.fnal.gov/wiki/Authentication#Certificate  and https://mu2ewiki.fnal.gov/wiki/DataTransfer#xrootd .

2024-05-30 03:04 UTC, FNALbuild commented
:umbrella: The build tests failed for 675286c197a8cb27c372bf98c96bdedd392331c0.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :x: | Failed to retrieve request base branch commit sha for Mu2e/mu2e_trig_config#28, default is to merge into main |
| test with | :white_check_mark: | Included Mu2e/mu2e_trig_config#28 @ 71a3ebb6f891bd54150b64959c627ac5fe3f9db2 by merge |
| merge | :white_check_mark: | Merged 675286c197a8cb27c372bf98c96bdedd392331c0 at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/scons.log). Build time: 10 min 44 sec |
| ceSimReco | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/ceSimReco.log) Return Code 134. |
| g4test_03MT | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/g4test_03MT.log) Return Code 134. |
| transportOnly | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/transportOnly.log) Return Code 134. |
| POT | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/POT.log) Return Code 134. |
| g4study | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/g4study.log) Return Code 134. |
| cosmicSimReco | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/cosmicSimReco.log) Return Code 134. |
| cosmicOffSpill | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/cosmicOffSpill.log) Return Code 134. |
| ceSteps | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/ceSteps.log) Return Code 134. |
| ceDigi | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/ceDigi.log) Return Code 134. |
| muDauSteps | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/muDauSteps.log) Return Code 134. |
| ceMix | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/ceMix.log) Return Code 134. |
| rootOverlaps | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/rootOverlaps.log) Return Code 134. |
| g4surfaceCheck | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/g4surfaceCheck.log) Return Code 134. |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 37 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 675286c197a8cb27c372bf98c96bdedd392331c0 after being merged into the base branch at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2116/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-05-30 03:11 UTC, kutschke commented
Hmmm.  Test with was not helpful.

2024-05-30 13:05 UTC, edcallaghan commented
@kutschke do you have a theory as to what's causing these slates of memory-related errors? Are these jobs running on AL9? The memory-map printout references an SL7 build, and when I test locally on an lbl machine running SL7 the jobs are successful.

2024-05-30 13:22 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 675286c197a8cb27c372bf98c96bdedd392331c0: build  (Build queue is empty)

2024-05-30 14:03 UTC, FNALbuild commented
:umbrella: The build tests failed for 675286c197a8cb27c372bf98c96bdedd392331c0.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 675286c197a8cb27c372bf98c96bdedd392331c0 at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/scons.log). Build time: 21 min 26 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/cosmicOffSpill.log) Return Code 9. |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/ceSteps.log)  |
| ceDigi | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/ceDigi.log) Return Code 9. |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/muDauSteps.log)  |
| ceMix | :x: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/ceMix.log) Return Code 9. |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 37 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 675286c197a8cb27c372bf98c96bdedd392331c0 after being merged into the base branch at 1fd70d38c02fc1dcf9fe36d86abc0491c4d76f20.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2117/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-05-30 14:29 UTC, kutschke commented
@edcallaghan  My experiment failed and we can ignore it.  

I suggest making the changes I suggested in mu2e_trig_config and testing locally.  If that works push to your mu2e_trig_config fork and we can merge mu2e_trig_config and rerun the CI.

2024-05-30 18:09 UTC, edcallaghan commented
Ok, well, with the latest commit to `mu2e_trig_config` which properly extends the `CstSimpleTimeCluster` defined therein from the default defined here in Offline, all of relevant validation jobs (i.e. `ceSteps`, `muDauSteps`, `ceDigi`, `ceMix`, and `cosmicOffSpill`) run and terminate without any errors.

2024-05-30 18:31 UTC, kutschke commented
Created issue #1277 to followup on adding an mock namespace to  CosmicReco/fcl/prolog.fcl.  That should be a separate PR.

2024-05-30 18:31 UTC, kutschke approved these changes

2024-06-01 15:30 UTC, kutschke commented
@edcallaghan since yesterday afternoon there have been intermittent issues with access to the cached DB server.  So any CI you run now will likely fail.   Our support is 5/8 but sometimes we get lucky over weekends.

2024-06-01 15:30 UTC, FNALbuild commented
:memo: The HEAD of `main` has changed to ee4ce2c72021c785098852071cdb5ef741977a15. Tests are now out of date.

2024-06-07 18:01 UTC, kutschke commented
The PR in mu2e_trig_config has been merged.  So the CI should work now

@FNALbuild run build test

2024-06-07 18:01 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 675286c197a8cb27c372bf98c96bdedd392331c0: build  (Build queue is empty)

2024-06-07 18:28 UTC, FNALbuild commented
:sunny: The build tests passed at 675286c197a8cb27c372bf98c96bdedd392331c0.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 675286c197a8cb27c372bf98c96bdedd392331c0 at fc6b3b1e954528ac4f5f8b3f0ad965633dc79e64 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/scons.log). Build time: 10 min 53 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 37 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 675286c197a8cb27c372bf98c96bdedd392331c0 after being merged into the base branch at fc6b3b1e954528ac4f5f8b3f0ad965633dc79e64.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2125/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-06-07 18:46 UTC, merged