Doctoring StrawDigi timing to shift tracks in time
Mu2e/Offline pull request #1344
Opened 2024-09-24 18:44 UTC by edcallaghan

This PR implements a module which coherently shifts the TDC values of a `StrawDigiCollection`, so as to shift the timing of any to-be-reconstructed tracks . This PR is marked as a draft for now; more detail will be added here before it's necessary to initiate review.

2024-09-24 18:44 UTC, FNALbuild commented
Hi @edcallaghan,
You have proposed changes to files in these packages:
- Blinding

which require these tests: build.

@Mu2e/write, @Mu2e/fnalbuild-users have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 7f295bbedb773089c2a3cc67645b1f6201800701: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2024-09-24 18:54 UTC, FNALbuild commented
:sunny: The build tests passed at 7f295bbedb773089c2a3cc67645b1f6201800701.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 7f295bbedb773089c2a3cc67645b1f6201800701 at 38f72f8ba512f3d8ef4cc5376606d7578001491f |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/scons.log). Build time: 04 min 17 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :large_orange_diamond: | [TODO (2) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 110 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 7f295bbedb773089c2a3cc67645b1f6201800701 after being merged into the base branch at 38f72f8ba512f3d8ef4cc5376606d7578001491f.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2261/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-10-04 19:40 UTC, FNALbuild commented
:memo: The HEAD of `main` has changed to 5694fbea850c699935590c6ed1e1fc2149d77b26. Tests are now out of date.

2025-01-03 19:36 UTC, edcallaghan commented
@bonventre Can you confirm that the tracker waveforms are time-invariant, i.e. if we are shifting the digi tdc values in time, we do not need to also adjust the position of the signal inside the waveforms?

2025-01-03 22:15 UTC, brownd1978 reviewed
I like the concept of shifting to an intersection time, but there are some details I'd like to understand, as that returns calibrated times, and the target is an extended object with multiple foils potentially intersected.

2025-01-03 22:15 UTC, brownd1978 commented on Blinding/src/DisplaceDigiTimes_module.cc
> +    double target_time = this->sample_target_time();
Does 'target_time' here refer to the physical stopping target? A KalSeed can intersect multiple foils, is the intent here to shift to a generic intersection, ignoring the specific foil? Or will the sampling time somehow take the foil into account?

2025-01-03 22:15 UTC, brownd1978 commented on Blinding/src/DisplaceDigiTimes_module.cc
> +    auto rv = electronics.tdcResponse(time);
What's the benefit of wrapping the electronics function here?

2025-01-03 22:15 UTC, brownd1978 commented on Blinding/src/DisplaceDigiTimes_module.cc
> +    auto rv = static_cast<double>(time) * electronics.tdcLSB();
should this function be moved to StrawElectronics?
Are there edge effects one needs to worry about? How about the channel-specific effects described [here](url)?

2025-01-03 22:25 UTC, edcallaghan commented
> I like the concept of shifting to an intersection time, but there are some details I'd like to understand, as that returns calibrated times, and the target is an extended object with multiple foils potentially intersected.

@brownd1978 I think we're better off using e.g. the time of the front of the tracker. (which I realize is not what one would glean from this PR) --- I wrote "target" in the mathematical sense, not the Mu2e meaning. As you say, we won't generally have one well-defined intersection with the target, and I don't think it's worth constructing a way to deal with that when it's at best isomorphic to using a different location which will have a unique intersection.

2025-01-03 22:33 UTC, edcallaghan commented on Blinding/src/DisplaceDigiTimes_module.cc
> +    auto rv = electronics.tdcResponse(time);
This is just for a symmetric and easy-to-parse interface, i.e. a non-expert could pick up "analog-to-digital" and "digital-to-analog" faster than "tdcResponse" and "tdcLSB."

2025-01-03 22:35 UTC, edcallaghan commented on Blinding/src/DisplaceDigiTimes_module.cc
> +    auto rv = static_cast<double>(time) * electronics.tdcLSB();
I don't feel strongly about shifting this into the electronics class or not. If there is any other use case for inverting (IMO, likely) then it would make sense to. Maybe @bonventre can comment on nuance that may be missing --- I just didn't see anything else in the existing electronics utility to make use of.

2025-01-03 22:37 UTC, edcallaghan commented on Blinding/src/DisplaceDigiTimes_module.cc
> +    double target_time = this->sample_target_time();
As I said in the out-of-thread comment, this was nomenclature clash (target of a mathematical operation vs stopping target). I think we use a location with a unique (at least, we expect unique) intersection. But we do have leeway in choosing where to sample, because the distribution we are shifting to is also within our control (and we can take it from data or MC as we see fit).

2025-01-09 06:32 UTC, brownd1978 approved these changes

2025-01-09 06:33 UTC, brownd1978 commented
@FNALbuild run build test

2025-01-09 06:33 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for ec19040202433ea86815fb513f7c5eaf562effdb: build  (Build queue is empty)

2025-01-09 06:42 UTC, FNALbuild commented
:sunny: The build tests passed at ec19040202433ea86815fb513f7c5eaf562effdb.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged ec19040202433ea86815fb513f7c5eaf562effdb at d0247a0d7199439409ff9359471bafa19e977aa0 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/scons.log). Build time: 04 min 25 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 2 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 216 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at ec19040202433ea86815fb513f7c5eaf562effdb after being merged into the base branch at d0247a0d7199439409ff9359471bafa19e977aa0.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2361/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2025-01-10 00:58 UTC, bonventre requested changes

2025-01-10 00:58 UTC, bonventre commented on Blinding/src/DisplaceDigiTimes_module.cc
> +    auto rv = static_cast<double>(time) * electronics.tdcLSB();
Right now this is missing _electronicsTimeDelay from strawelectronics. I think this is a redundant parameter that is set to zero and can be removed, but for now maybe its easier to put this function in strawelectronics and add this offset back in there.

2025-01-10 19:59 UTC, bonventre approved these changes

2025-01-10 21:04 UTC, brownd1978 reviewed
One final comment: given my confusion about the term 'target' and given this code will be used as a template for others, can you swap in a different term for where the timing is sampled? Maybe 'reference'?

2025-01-13 21:01 UTC, merged