adding helix propagation direction info into HelixSeed/HelixRecoDir, and implementing it into AgnosticHelixFinder
Mu2e/Offline pull request #1359
Opened 2024-10-10 20:41 UTC by matthewstortini

Now in AgnosticHelixFinder you have a fhicl::Sequence<std::string> validHelixDirections parameter, as well as a fhicl::Atom<float> tzSlopeSigThresh parameter.

In the Offline I've set validHelixDirections : ["downstream", "upstream", "ambiguous"] ... could imagine in the trigger we have ["downstream", "ambiguous"]. 

For tz slope significance (std::abs(tzSlope/tzSlopeErr) < tzSlopeSigThresh we consider the helix direction "ambiguous".

Other helix modules can follow the same process that AgnosticHelixFinder is following by using the new tools implemented. The HelixRecoDir::PropDir _propDir data member in the HelixSeed can be set with:

    HelixTool helTool(&hseed,_tracker);
    float tzSlope = 0.0;
    float tzSlopeErr = 0.0;
    float tzSlopeChi2 = 0.0;
    helTool.dirOfProp(tzSlope, tzSlopeErr, tzSlopeChi2);
    HelixRecoDir helDir(tzSlope, tzSlopeErr, tzSlopeChi2);
    hseed._recoDir = helDir;
    hseed._propDir = helDir.computeDirection(_tzSlopeSigThresh);

2024-10-10 20:42 UTC, FNALbuild commented
Hi @matthewstortini,
You have proposed changes to files in these packages:
- CalPatRec
- RecoDataProducts

which require these tests: build.

@Mu2e/write, @Mu2e/fnalbuild-users have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 38cf10d60619c3113b9b73e048799bb920aac32d: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2024-10-10 20:58 UTC, FNALbuild commented
:sunny: The build tests passed at 38cf10d60619c3113b9b73e048799bb920aac32d.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 38cf10d60619c3113b9b73e048799bb920aac32d at 733b2e5a53eba96f84e2dbfe6e2ac8482e1d19c4 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/scons.log). Build time: 08 min 31 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 3 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/fixme_todo.log) |
| clang-tidy | :large_orange_diamond: | [0 errors 183 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 38cf10d60619c3113b9b73e048799bb920aac32d after being merged into the base branch at 733b2e5a53eba96f84e2dbfe6e2ac8482e1d19c4.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//2287/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2024-10-10 20:59 UTC, gianipez commented
Thank you, @matthewstortini . tagging @brownd1978

2024-10-10 21:14 UTC, gianipez commented
I can take care of CalHelixFinder once this PR gets merged

2024-10-12 23:36 UTC, FNALbuild commented
:memo: The HEAD of `main` has changed to 5e6bdb0c35b45c547469e286d28da0f9396f6c0d. Tests are now out of date.

2024-10-13 13:55 UTC, brownd1978 requested changes
I request some changes to enum handling, otherwise this looks good.

2024-10-13 13:55 UTC, brownd1978 commented on CalPatRec/src/AgnosticHelixFinder_module.cc
> +      if (_validHelixDirections.at(i) == hDir) return true;
Using strings for this comparison is inefficient. Why not just test the value (as an int) is within the enum range?
What situation is this logic trying to protect against? Normally, an enum should never have  a value outside its pre-defined range, unless you have hard-cast it from an int. If you can avoid that use case you can avoid even needing this function.

2024-10-13 13:55 UTC, brownd1978 commented on RecoDataProducts/inc/HelixRecoDir.hh
> +    PropDir computeDirection(float sigThreshold) const {
This function name is misleading, the direction (slope) isn't being computed, just compared. slopeSignificance?

2024-10-13 13:55 UTC, brownd1978 commented on RecoDataProducts/inc/HelixRecoDir.hh
> +      upstream,
Please specify at least the initial value. It would be intuitive if you set ambiguous=0, downstream=1, upstream=-1

2024-10-14 21:35 UTC, matthewstortini commented
I think all the comments have been addressed. Let me know if anything else is desired.

2024-10-15 17:34 UTC, brownd1978 approved these changes
Thanks for making the changes.

2024-10-15 17:35 UTC, brownd1978 commented
@FNALbuild run build test

2024-10-15 17:35 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 813b446b10fa74696d2645695a0a0065af1daa43: build  (Build queue is empty)

2024-10-15 18:01 UTC, merged