RNs seeds in G4MT are now handled by us. We use Crypto++ to create ha…
Mu2e/Offline pull request #301
Opened 2020-12-17 16:04 UTC by goodenou

…shes for seeds based on art::event ID (Run#, Subrun#, Event#).

2020-12-17 16:04 UTC, FNALbuild commented
Hi @goodenou,
You have proposed changes to files in these packages:
- /
- Mu2eG4

which require these tests: build.

@Mu2e/write, @Mu2e/fnalbuild-users have access to CI actions on [master](/Mu2e/Offline/tree/master).

The following users requested to be notified about changes to these packages:
@resnegfk
:hourglass: The following tests have been triggered for 8556d3137045af6a137cc8f865ede3849b2cc924: build  (Build queue has 1 jobs)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/Git#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2020-12-17 16:27 UTC, FNALbuild commented
:sunny: The tests passed at ref 8556d3137045af6a137cc8f865ede3849b2cc924.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :heavy_check_mark: | Merged 8556d3137045af6a137cc8f865ede3849b2cc924 at 13eedec808fe1c7a1eb4b8b284baee5362c91792 |
| scons build (prof) | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/scons.log). Build time: 13 min 58 sec |
| ceSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/ceSimReco.log) |
| transportOnly | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/transportOnly.log) |
| PS | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/PS.log) |
| g4study | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/g4study.log) |
| cosmicSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/cosmicSimReco.log) |
| rootOverlaps | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/rootOverlaps.log) |
| g4surfaceCheck | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/g4surfaceCheck.log) |
| FIXME, TODO count | :wavy_dash: | [TODO (0) FIXME (1) in 6 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 16 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/artifact/clang-tidy.log) |


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//318/console).
Build artefacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.


Logfiles may also be accessed [at this link.](https://gist.github.com/cad2dbd4441a58389ed3fd721258ab15)

2020-12-17 19:47 UTC, kutschke commented
Lisa: thanks for closing this PR making this second PR - the history post merge is infinitely less confusing now.

Andrei: you added review comments in the "File Changed: tag of the earlier, now closed, PR.  Please go back to that tab and check each issue - if they are resolved to your satisfaction, please click on the "Resolve conversation" button for each of them.   When you are done, please approve this PR.

2020-12-17 20:03 UTC, kutschke commented
Lisa: I should also have added that you should look at Andrei's comments in the old PR and, if they need a response, reply to them so that he can resolve them.

I resolved the conversation on my SConscript comment.

2020-12-17 20:06 UTC, goodenou commented
I believe I answered all of his comments, but I will check again.

> On Dec 17, 2020, at 2:04 PM, Rob Kutschke <notifications@github.com> wrote:
> 
> 
> Lisa: I should also have added that you should look at Andrei's comments in the old PR and, if they need a response, reply to them so that he can resolve them.
> 
> I resolved the conversation on my SConscript comment.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Mu2e/Offline/pull/301#issuecomment-747670312>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AE44QBWZG2LLNEJKV25AV2DSVJP3TANCNFSM4U74CDIQ>.
>

2020-12-17 20:07 UTC, kutschke commented
@FNALbuild run build tests

2020-12-17 20:08 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for d5a2168a26762a834ae726418a48350829e49154: build  (Build queue has 6 jobs)

2020-12-17 20:19 UTC, gaponenko requested changes
I would like to understand whether there is a memory leak, and also ask for code changes.  Please see the inline comments.

2020-12-17 20:19 UTC, gaponenko commented on setup.sh
> +export MU2E_ART_SQUALIFIER=s101
Please undo changes to setup.sh - I do not think these should go in.

2020-12-17 20:19 UTC, gaponenko commented on Mu2eG4/inc/Mu2eG4WorkerRunManager.hh
> +    G4Event* generateEvt(art::EventID);
Suggest const art::EventID& instead of art::EventID here to avoid making copies, for both functions.

2020-12-17 20:19 UTC, gaponenko commented on Mu2eG4/src/Mu2eG4WorkerRunManager.cc
> +    CryptoPP::StringSource(digest, true, new CryptoPP::Redirector(encoder_out));
Same question as before:  this looks like new-ing some objects and never deleting them.  How is memory managed here?

2020-12-17 20:31 UTC, FNALbuild commented
:sunny: The tests passed at ref d5a2168a26762a834ae726418a48350829e49154.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :heavy_check_mark: | Merged d5a2168a26762a834ae726418a48350829e49154 at 13eedec808fe1c7a1eb4b8b284baee5362c91792 |
| scons build (prof) | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/scons.log). Build time: 13 min 59 sec |
| ceSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/ceSimReco.log) |
| transportOnly | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/transportOnly.log) |
| PS | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/PS.log) |
| g4study | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/g4study.log) |
| cosmicSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/cosmicSimReco.log) |
| rootOverlaps | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/rootOverlaps.log) |
| g4surfaceCheck | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/g4surfaceCheck.log) |
| FIXME, TODO count | :wavy_dash: | [TODO (0) FIXME (1) in 6 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 16 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/artifact/clang-tidy.log) |


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//321/console).
Build artefacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.


Logfiles may also be accessed [at this link.](https://gist.github.com/9976f72c98ac790902a39e64fe740849)

2020-12-17 20:35 UTC, kutschke commented
> I believe I answered all of his comments, but I will check again.
> […](#

I am still learning about the best ways to use github.  There are at least two ways to make comments: open a comment a line in a code listing on the “files changed” tab or comment in the box at the bottom of the conversation tab.   If you do the former it starts a thread that github organizes as a thread – it’s the thread that has the resolve conversation button.  If you comment in the box at the bottom of the conversation tab, it is not part of any thread, just a part of the whole conversation.   If you reply that way we don’t have the assistance of github to match it to the original comment.

I was asked that you reply to Andrei's in code comments within the thread that each started.

2020-12-17 20:49 UTC, goodenou commented
Rob,
I see three comments from Andrei and I replied to them all. Two were in-line/thread comments and one was not. I don’t know how to make the one that was not a thread comment into a thread comment.


Lisa




> On Dec 17, 2020, at 2:35 PM, Rob Kutschke <notifications@github.com> wrote:
> 
> 
> I believe I answered all of his comments, but I will check again.
> […](#
> 
> I am still learning about the best ways to use github. There are at least two ways to make comments: open a comment a line in a code listing on the “files changed” tab or comment in the box at the bottom of the conversation tab. If you do the former it starts a thread that github organizes as a thread – it’s the thread that has the resolve conversation button. If you comment in the box at the bottom of the conversation tab, it is not part of any thread, just a part of the whole conversation. If you reply that way we don’t have the assistance of github to match it to the original comment.
> 
> I was asked that you reply to Andrei's in code comments within the thread that each started.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Mu2e/Offline/pull/301#issuecomment-747686857>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AE44QBSE66YBIXEOM6SPXJ3SVJTR7ANCNFSM4U74CDIQ>.
>

2020-12-17 22:50 UTC, kutschke commented
@FNALbuild run build tests

2020-12-17 22:50 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 686891cc6ca42209cb1219ef9cbd127406e031bc: build  (Build queue has 3 jobs)

2020-12-17 23:14 UTC, FNALbuild commented
:sunny: The tests passed at ref 686891cc6ca42209cb1219ef9cbd127406e031bc.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :heavy_check_mark: | Merged 686891cc6ca42209cb1219ef9cbd127406e031bc at 762ca28040a5de3106535eb59c4e37e73e9aae5d |
| scons build (prof) | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/scons.log). Build time: 14 min 46 sec |
| ceSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/ceSimReco.log) |
| transportOnly | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/transportOnly.log) |
| PS | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/PS.log) |
| g4study | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/g4study.log) |
| cosmicSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/cosmicSimReco.log) |
| rootOverlaps | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/rootOverlaps.log) |
| g4surfaceCheck | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/g4surfaceCheck.log) |
| FIXME, TODO count | :wavy_dash: | [TODO (0) FIXME (1) in 6 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 16 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/artifact/clang-tidy.log) |


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//322/console).
Build artefacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.


Logfiles may also be accessed [at this link.](https://gist.github.com/cc25696a1e9f47911ff1e90d5d834f04)

2020-12-17 23:45 UTC, kutschke commented
Lisa and Andrei: what do each of you think is left to resolve, if anything?

2020-12-18 01:39 UTC, goodenou commented
I think I have addressed all of Andrei’s suggestions and questions.

> On Dec 17, 2020, at 5:45 PM, Rob Kutschke <notifications@github.com> wrote:
> 
> 
> Lisa and Andrei: what do each of you think is left to resolve, if anything?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Mu2e/Offline/pull/301#issuecomment-747775836>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AE44QBS7YOV3RU2MMYANYJDSVKJ2LANCNFSM4U74CDIQ>.
>

2020-12-18 06:01 UTC, gaponenko approved these changes
Lisa, thank you for updating the PR.   Rob, please merge.

2020-12-18 06:10 UTC, merged