Cosmic renaming
Mu2e/Offline pull request #369
Opened 2021-03-05 21:31 UTC by soleti

I propose the following changes to the Cosmic FCL file names to agree with the MDC2020 conventions.

2021-03-05 21:32 UTC, FNALbuild commented
Hi @soleti,
You have proposed changes to files in these packages:
- JobConfig

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [master](/Mu2e/Offline/tree/master).


:hourglass: The following tests have been triggered for 7f2baf7f172eafb9348aeb75e8c0f895dfb8b187: build  (Build queue has 3 jobs)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/Git#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2021-03-05 21:32 UTC, FNALbuild commented
:bangbang: The build test could not run due to merge conflicts. Please resolve these first and try again.
```
> git diff --check | grep -i conflict
JobConfig/cosmic/S2Converter.fcl:25: leftover conflict marker
JobConfig/cosmic/S2Converter.fcl:31: leftover conflict marker
JobConfig/cosmic/S2Converter.fcl:33: leftover conflict marker
```

2021-03-06 12:55 UTC, oksuzian requested changes
Roberto, thank you for doing this!
Please consider making minor changes to file names.

2021-03-06 12:55 UTC, oksuzian commented on JobConfig/cosmic/S2ResamplerHigh.fcl
> -outputs.Output.fileName        : "sim.owner.cosmic-s2-resampler-hi.version.sequencer.art"
Can we name it as:
sim.owner.CosmicHi.version.sequencer.art

2021-03-06 12:55 UTC, oksuzian commented on JobConfig/cosmic/S2ResamplerLow.fcl
> +outputs.Output.fileName        : "sim.owner.Cosmic.version.sequencer.art"
Can we name it as:
sim.owner.CosmicLo.version.sequencer.art

2021-03-06 13:11 UTC, brownd1978 approved these changes

2021-03-09 18:45 UTC, oksuzian approved these changes
Looks good. Thanks, Roberto.

2021-03-09 19:58 UTC, FNALbuild commented
:sunny: The tests passed at ref 35f2d001fb10d9ece3888dde6bef8ff6c4f22241.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :heavy_check_mark: | Merged 35f2d001fb10d9ece3888dde6bef8ff6c4f22241 at 37fed006d5d39c35e2c6cb8743615c3fd1044395 |
| scons build (prof) | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/scons.log). Build time: 14 min 54 sec |
| ceSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/ceSimReco.log) |
| transportOnly | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/transportOnly.log) |
| PS | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/PS.log) |
| g4study | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/g4study.log) |
| cosmicSimReco | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/cosmicSimReco.log) |
| rootOverlaps | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/rootOverlaps.log) |
| g4surfaceCheck | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/g4surfaceCheck.log) |
| g4test_03MT | :heavy_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/g4test_03MT.log) |
| FIXME, TODO count | :heavy_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/fixme_todo.log) |
| clang-tidy | :heavy_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/artifact/clang-tidy.log) |


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//435/console).
Build artefacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-03-09 23:43 UTC, merged