Jobconfig dependence cleanup
Mu2e/Offline pull request #434
Opened 2021-04-30 20:43 UTC by rlcee

- implement what I can from recommendations in Issue #426 
- Probably only remaining important item before splitting JobConfig is resolving the event display

2021-04-30 20:44 UTC, FNALbuild commented
Hi @rlcee,
You have proposed changes to files in these packages:
- Mu2eG4
- TrkPatRec
- EventGenerator
- Mu2eKinKal
- Analyses

which require these tests: build.

@Mu2e/write, @Mu2e/fnalbuild-users have access to CI actions on [master](/Mu2e/Offline/tree/master).

The following users requested to be notified about changes to these packages:
@resnegfk



:hourglass: The following tests have been triggered for 115f7351e47a0cd1a2f396da412bf490502e7432: build  (Build queue has 2 jobs)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/Git#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2021-04-30 21:06 UTC, FNALbuild commented
:umbrella: The tests failed for 115f7351e47a0cd1a2f396da412bf490502e7432.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 115f7351e47a0cd1a2f396da412bf490502e7432 at c17881953419f2c7a7c4cb2f308c466fa44d631c |
| scons build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/scons.log). Build time: 13 min 46 sec |
| ceSimReco | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/ceSimReco.log) |
| g4test_03MT | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/g4test_03MT.log) |
| transportOnly | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/transportOnly.log) |
| PS | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/PS.log) |
| g4study | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/g4study.log) |
| cosmicSimReco | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/cosmicSimReco.log) |
| ceSteps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/ceSteps.log) |
| ceDigi | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/ceDigi.log) |
| muSteps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/muSteps.log) |
| ceMix | :x: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/ceMix.log) |
| rootOverlaps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/rootOverlaps.log) |
| g4surfaceCheck | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/g4surfaceCheck.log) |
| FIXME, TODO count | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/artifact/clang-tidy.log) |


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//548/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-04-30 21:52 UTC, FNALbuild commented
:memo: The HEAD of `master` has changed to 63608413434e92c96d8de6a9d30f7292d94b8490. Tests are now out of date.

2021-04-30 22:08 UTC, brownd1978 approved these changes

2021-04-30 23:31 UTC, resnegfk requested changes
If we move  Mu2eG4/fcl/iontest_g4s2.fcl, we should also move the two other iontest*.fcl files
I would really suggest to make list of what goes where before doing the actual moves

2021-05-01 01:33 UTC, rlcee commented
@FNALbuild run build test

2021-05-01 01:34 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 115f7351e47a0cd1a2f396da412bf490502e7432: build  (Build queue has 1 jobs)

2021-05-01 02:01 UTC, FNALbuild commented
:sunny: The tests passed at 115f7351e47a0cd1a2f396da412bf490502e7432.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 115f7351e47a0cd1a2f396da412bf490502e7432 at 63608413434e92c96d8de6a9d30f7292d94b8490 |
| scons build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/scons.log). Build time: 13 min 36 sec |
| ceSimReco | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/ceSimReco.log) |
| g4test_03MT | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/g4test_03MT.log) |
| transportOnly | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/transportOnly.log) |
| PS | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/PS.log) |
| g4study | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/g4study.log) |
| cosmicSimReco | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/cosmicSimReco.log) |
| ceSteps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/ceSteps.log) |
| ceDigi | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/ceDigi.log) |
| muDauSteps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/muDauSteps.log) |
| ceMix | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/ceMix.log) |
| rootOverlaps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/rootOverlaps.log) |
| g4surfaceCheck | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/g4surfaceCheck.log) |
| FIXME, TODO count | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/artifact/clang-tidy.log) |


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//549/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-05-03 17:21 UTC, resnegfk approved these changes

2021-05-05 19:11 UTC, brownd1978 commented
@FNALbuild run build test

2021-05-05 19:12 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 541026afdcfed562307122b9811f912b33ed0b6d: build  (Build queue has 3 jobs)

2021-05-05 19:41 UTC, FNALbuild commented
:sunny: The tests passed at 541026afdcfed562307122b9811f912b33ed0b6d.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 541026afdcfed562307122b9811f912b33ed0b6d at b53c841cf5dc80a488d4363db5d51f09dafeaaf6 |
| scons build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/scons.log). Build time: 16 min 32 sec |
| ceSimReco | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/ceSimReco.log) |
| g4test_03MT | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/g4test_03MT.log) |
| transportOnly | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/transportOnly.log) |
| PS | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/PS.log) |
| g4study | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/g4study.log) |
| cosmicSimReco | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/cosmicSimReco.log) |
| ceSteps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/ceSteps.log) |
| ceDigi | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/ceDigi.log) |
| muDauSteps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/muDauSteps.log) |
| ceMix | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/ceMix.log) |
| rootOverlaps | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/rootOverlaps.log) |
| g4surfaceCheck | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/g4surfaceCheck.log) |
| FIXME, TODO count | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/artifact/clang-tidy.log) |


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//554/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-05-06 15:09 UTC, merged