Combo hit
Mu2e/Offline pull request #521
Opened 2021-07-06 00:23 UTC by bechenard

July 4th gift for Dave

2021-07-06 00:24 UTC, FNALbuild commented
Hi @bechenard,
You have proposed changes to files in these packages:
- TrkHitReco

which require these tests: build.

@Mu2e/write, @Mu2e/fnalbuild-users have access to CI actions on [master](/Mu2e/Offline/tree/master).





:hourglass: The following tests have been triggered for d8e5e39b16efe2d15a030e11d9cda4a44f3578ef: build  (Build queue has 1 jobs)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2021-07-06 00:57 UTC, FNALbuild commented
:sunny: The tests passed at d8e5e39b16efe2d15a030e11d9cda4a44f3578ef.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged d8e5e39b16efe2d15a030e11d9cda4a44f3578ef at 99cc589ce113eeb629a080c29362595f9baad240 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/scons.log). Build time: 16 min 19 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at d8e5e39b16efe2d15a030e11d9cda4a44f3578ef after being merged into the base branch at 99cc589ce113eeb629a080c29362595f9baad240.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//795/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-07-06 01:22 UTC, brownd1978 requested changes
Hi Bertrand, I guess the point of this PR is replacing the boost accumulators, not just re-indenting?  Sorry to be a nag, but the rule is that code without validated fhicl needs to migrated when it is changed.

2021-07-06 02:33 UTC, bechenard commented
Hi Dave,

What is the coefficient of elasticity of this rule? I did replace the 
accumulators and changed some of the logic to make it easier to maintain.

Cheers,

Bertrand

On 7/5/2021 6:22 PM, David Brown wrote:
>
> ***@***.**** requested changes on this pull request.
>
> Hi Bertrand, I guess the point of this PR is replacing the boost 
> accumulators, not just re-indenting? Sorry to be a nag, but the rule 
> is that code without validated fhicl needs to migrated when it is changed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/521#pullrequestreview-699468557>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JGWQHGCLT2BM5XHVY3TWJLEVANCNFSM473QUHLQ>.
>

2021-07-07 02:16 UTC, bechenard commented
I fixed the fhicl validation, and hopefully all instances in the prologs. My limited tests worked, but let me know if there is an issue.

2021-07-14 21:34 UTC, brownd1978 commented
@FNALbuild run build tests

2021-07-14 21:35 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 2a9ab95d6679afac3d505d32f36ab26e4d4b61ba: build  (Build queue has 4 jobs)

2021-07-14 21:35 UTC, FNALbuild commented
:bangbang: It was not possible to prepare the workspace for this test. This is often caused by merge conflicts - please check and try again.
```
> git diff --check | grep -i conflict
TrkHitReco/src/CombineStrawHits_module.cc:9: leftover conflict marker
TrkHitReco/src/CombineStrawHits_module.cc:13: leftover conflict marker
TrkHitReco/src/CombineStrawHits_module.cc:18: leftover conflict marker
```

| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :x: | 2a9ab95d6679afac3d505d32f36ab26e4d4b61ba into 0f4af86d6357bd223d0131d7584e5c7e89c8acd9 merge failed |

2021-07-14 21:42 UTC, bonventre commented on TrkHitReco/src/CombineStrawHits_module.cc
> +for (auto& ch : *chcolNew) std::cout<<ch.time()<<" "<<ch.pos()<<std::endl;
Looks like some leftover debugging print statements

2021-07-14 21:43 UTC, bechenard commented
Crap, I was certain to have removed them... I'll fix this later.

Bertrand

On 7/14/2021 2:42 PM, Richie Bonventre wrote:
>
> ***@***.**** commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In TrkHitReco/src/CombineStrawHits_module.cc 
> <https://github.com/Mu2e/Offline/pull/521#discussion_r669974737>:
>
> > -          used[ihit] = true;
> -          ComboHit const& hit1 = (*_chcol)[phits[ihit]];
> -          // create a combo hit for every hit; initialize it with this hit
> +      // I have to get a Handle, not a ValidHandle, as a literal handle is needed to find the productID
> +      art::Handle<ComboHitCollection> chH;
> +      if(!event.getByLabel(_chTag, chH))
> +        throw cet::exception("RECO")<<"mu2e::CombineStrawHits: No ComboHit collection found for tag" <<  _chTag << std::endl;
> +      const ComboHitCollection* chcolOrig = chH.product();
> +
> +      auto chcolNew = std::make_unique<ComboHitCollection>();
> +      chcolNew->reserve(chcolOrig->size());
> +      chcolNew->setParent(chH);
> +
> +      combine(chcolOrig, *chcolNew);
> +std::cout<<"CH "<<chcolNew->size()<<std::endl;
> +for (auto& ch : *chcolNew) std::cout<<ch.time()<<" "<<ch.pos()<<std::endl;
>
> Looks like some leftover debugging print statements
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/521#pullrequestreview-706745820>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JBHGUV7ZE6SJZ6BJADTXYAEJANCNFSM473QUHLQ>.
>

2021-07-15 15:38 UTC, kutschke commented
Bertrand:  The conflict is generated by the "Offline shift" and will be straightforward to fix: just add Offline/ as a prefix to all includes in CombineStrawHits_module.cc .  Probably the easiest thing is to merge/rebase.  If this PR is otherwise really complete we can fix it on the GitHub website with the online editor - but I don't know what happens if we fix it there and you decide you need another commit on this PR.  Do you want to use this as a chance to learn what happens?

2021-07-15 17:36 UTC, bechenard commented
Hi Rob,

I fixed ComboHits, but FastCaloCluster will require more work (I'll 
cancel the PR and remake one when it's ready). I'm away until the end of 
July and will have limited time to work on this.

Cheers,

Bertrand

On 7/15/2021 8:38 AM, Rob Kutschke wrote:
>
> Bertrand: The conflict is generated by the "Offline shift" and will be 
> straightforward to fix: just add Offline/ as a prefix to all includes 
> in CombineStrawHits_module.cc . Probably the easiest thing is to 
> merge/rebase. If this PR is otherwise really complete we can fix it on 
> the GitHub website with the online editor - but I don't know what 
> happens if we fix it there and you decide you need another commit on 
> this PR. Do you want to use this as a chance to learn what happens?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/521#issuecomment-880800226>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JBBUJNWDXGARB3P5I3TX36I5ANCNFSM473QUHLQ>.
>

2021-07-15 19:01 UTC, kutschke commented
@FNALbuild run build tests

2021-07-15 19:02 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 61db19f3afd0011641ecad71686039172d7da32a: build  (Build queue has 2 jobs)

2021-07-15 19:18 UTC, FNALbuild commented
:umbrella: The build is failing at 61db19f3afd0011641ecad71686039172d7da32a.

```
scons: *** [build/sl7-prof-e20-p008/Offline/tmp/TrkHitReco/src/CombineStrawHits_module.os] Error 1
```


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 61db19f3afd0011641ecad71686039172d7da32a at 0f4af86d6357bd223d0131d7584e5c7e89c8acd9 |
| build (prof) | :x: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/scons.log).  |
| ceSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/ceSimReco.log)  |
| g4test_03MT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/g4test_03MT.log)  |
| transportOnly | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/transportOnly.log)  |
| POT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/POT.log)  |
| g4study | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/g4study.log)  |
| cosmicSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/cosmicOffSpill.log)  |
| ceSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/ceSteps.log)  |
| ceDigi | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/ceDigi.log)  |
| muDauSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/muDauSteps.log)  |
| ceMix | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/ceMix.log)  |
| rootOverlaps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at 61db19f3afd0011641ecad71686039172d7da32a after being merged into the base branch at 0f4af86d6357bd223d0131d7584e5c7e89c8acd9.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//816/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-07-15 19:31 UTC, kutschke commented
This CI build failed because the code still has one old style include statement.  See:

https://github.com/bechenard/Offline/blob/61db19f3afd0011641ecad71686039172d7da32a/TrkHitReco/src/CombineStrawHits_module.cc#L13

The same file is already properly included 4 lines earlier.  Just delete this line, commit and push.  Then I will relaunch the CI.

2021-07-15 23:19 UTC, bechenard commented
Either very late tonight or this weekend. Feel free to do it if you can

Sent from my iPhone

> On Jul 15, 2021, at 12:31 PM, Rob Kutschke ***@***.***> wrote:
> 
> This CI build failed because the code still has one old style include statement. See:
> 
> https://github.com/bechenard/Offline/blob/61db19f3afd0011641ecad71686039172d7da32a/TrkHitReco/src/CombineStrawHits_module.cc#L13
> 
> The same file is already properly included 4 lines earlier. Just delete this line, commit and push. Then I will relaunch the CI.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-15 23:19 UTC, FNALbuild commented
:memo: The HEAD of `master` has changed to dd5cf950493d36f102973482458ff503f5de21e7. Tests are now out of date.

2021-07-16 00:32 UTC, kutschke commented
I don't know how to fix this one from the GitHub end.  I can only do that in a subset of the cases that GitHub detects a conflict.  In this case GitHub gives it the green light but our CI fails during the build.  So whenever you get to it.

2021-07-18 04:58 UTC, bechenard commented
Ok, made the fix, that should do it.

2021-07-18 21:34 UTC, brownd1978 commented
@FNALbuild run build tests

2021-07-18 21:34 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for c2917e2beab174f11fec4d91147a9d8d2a00b6fb: build  (Build queue has 1 jobs)

2021-07-18 21:41 UTC, bechenard commented
Ok, now it is really gone...

Bertrand

On 7/14/2021 2:42 PM, Richie Bonventre wrote:
>
> ***@***.**** commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In TrkHitReco/src/CombineStrawHits_module.cc 
> <https://github.com/Mu2e/Offline/pull/521#discussion_r669974737>:
>
> > -          used[ihit] = true;
> -          ComboHit const& hit1 = (*_chcol)[phits[ihit]];
> -          // create a combo hit for every hit; initialize it with this hit
> +      // I have to get a Handle, not a ValidHandle, as a literal handle is needed to find the productID
> +      art::Handle<ComboHitCollection> chH;
> +      if(!event.getByLabel(_chTag, chH))
> +        throw cet::exception("RECO")<<"mu2e::CombineStrawHits: No ComboHit collection found for tag" <<  _chTag << std::endl;
> +      const ComboHitCollection* chcolOrig = chH.product();
> +
> +      auto chcolNew = std::make_unique<ComboHitCollection>();
> +      chcolNew->reserve(chcolOrig->size());
> +      chcolNew->setParent(chH);
> +
> +      combine(chcolOrig, *chcolNew);
> +std::cout<<"CH "<<chcolNew->size()<<std::endl;
> +for (auto& ch : *chcolNew) std::cout<<ch.time()<<" "<<ch.pos()<<std::endl;
>
> Looks like some leftover debugging print statements
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/521#pullrequestreview-706745820>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JBHGUV7ZE6SJZ6BJADTXYAEJANCNFSM473QUHLQ>.
>

2021-07-18 22:06 UTC, FNALbuild commented
:sunny: The tests passed at c2917e2beab174f11fec4d91147a9d8d2a00b6fb.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged c2917e2beab174f11fec4d91147a9d8d2a00b6fb at dd5cf950493d36f102973482458ff503f5de21e7 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/scons.log). Build time: 14 min 10 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at c2917e2beab174f11fec4d91147a9d8d2a00b6fb after being merged into the base branch at dd5cf950493d36f102973482458ff503f5de21e7.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//828/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-07-19 19:57 UTC, kutschke commented
@FNALbuild run build tests

2021-07-19 19:57 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 2b2e7450489fab327b354077e26b26163c8a5c58: build  (Build queue has 1 jobs)

2021-07-19 20:29 UTC, FNALbuild commented
:sunny: The tests passed at 2b2e7450489fab327b354077e26b26163c8a5c58.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 2b2e7450489fab327b354077e26b26163c8a5c58 at dd5cf950493d36f102973482458ff503f5de21e7 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/scons.log). Build time: 14 min 36 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at 2b2e7450489fab327b354077e26b26163c8a5c58 after being merged into the base branch at dd5cf950493d36f102973482458ff503f5de21e7.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//832/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2021-07-20 00:00 UTC, brownd1978 approved these changes

2021-07-20 00:13 UTC, bonventre commented on TrkHitReco/src/CombineStrawHits_module.cc
> +              if (hit2.strawId().straw()-hit1.strawId().straw()> _maxds ) break;
Don't we still need an abs() here?

2021-07-20 05:30 UTC, bechenard commented
Hi Richie,

According to Dave, there is a guarantee that the hits are ordered by 
panels/straws/... , so strawID of hit2 is always >= strawID of hit1. But 
I should triple check.

Cheers,

Bertrand

On 7/19/2021 5:13 PM, Richie Bonventre wrote:
>
> ***@***.**** commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In TrkHitReco/src/CombineStrawHits_module.cc 
> <https://github.com/Mu2e/Offline/pull/521#discussion_r672716154>:
>
> > -            chcol->push_back(std::move(combohit));
> -        } // 1st hit not used
> -      } // 1st panel hit
> -    } // panels
> -    // store data in the event
> -    event.put(std::move(chcol));
> +          combohit.init(hit1,ich);
> +          int panel1 = hit1.strawId().uniquePanel();
> +
> +          for (size_t jch=ich+1;jch<chcolOrig->size();++jch)
> +          {
> +              if (isUsed[jch]) continue;
> +              const ComboHit& hit2 = (*chcolOrig)[jch];
> +
> +              if (hit2.strawId().uniquePanel() != panel1) break;
> +              if (hit2.strawId().straw()-hit1.strawId().straw()> _maxds ) break;
>
> Don't we still need an abs() here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/521#pullrequestreview-710079628>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JENHPSPS3PYQNZQP2TTYS5R5ANCNFSM473QUHLQ>.
>

2021-07-20 17:03 UTC, bonventre approved these changes

2021-07-21 14:48 UTC, merged