Update installTableFile.sh
Mu2e/Offline pull request #716
Opened 2022-02-17 21:57 UTC by eflumerf

Put the Offline bin directory in PATH

2022-02-17 22:01 UTC, FNALbuild commented
Hi @eflumerf,
You have proposed changes to files in these packages:
- ups_install

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 237cbe12bd0aeb4ec71c0fe644844712a5b5be4a: build  (Build queue has 5 jobs)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2022-02-17 22:04 UTC, kutschke requested changes

2022-02-17 22:04 UTC, kutschke commented on ups_install/installTableFile.sh
> +    pathPrepend(PATH, "\${OFFLINE_DIR}/\${OFFLINE_FQ}/bin")
I just setup the product and tried

ls ${OFFLINE_DIR}/${OFFLINE_FQ_DIR}/bin

It looks like Offline_FQ is not defined correctly - it's missing the "trigger" piece.

2022-02-17 22:06 UTC, eflumerf commented
`ls ${OFFLINE_DIR}/${OFFLINE_FQ}/bin` works for me using the product on CVMFS...note that it's `$OFFLINE_FQ` not `$OFFLINE_FQ_DIR`

2022-02-17 22:19 UTC, kutschke commented
> `ls ${OFFLINE_DIR}/${OFFLINE_FQ}/bin` works for me using the product on CVMFS...note that it's `$OFFLINE_FQ` not `$OFFLINE_FQ_DIR`

Ooops.  My apoligies

Three mistakes on my part.  First a typo: I did use OFFLINE_FQ.  Second when I did the setup I forgot trig in qualifiers.  Third I did not use setup in paranoid mode with -B and "+" on each qualifier.

2022-02-17 22:19 UTC, kutschke commented on ups_install/installTableFile.sh
> +    pathPrepend(PATH, "\${OFFLINE_DIR}/\${OFFLINE_FQ}/bin")
This is ok it was a mistake on my part - see the conversation.  Resolving this now.

2022-02-17 22:20 UTC, kutschke approved these changes

2022-02-17 22:28 UTC, FNALbuild commented
:sunny: The tests passed at 237cbe12bd0aeb4ec71c0fe644844712a5b5be4a.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 237cbe12bd0aeb4ec71c0fe644844712a5b5be4a at 7ccf66c69acad0ca8cf8028260f65fe36eb5be20 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/scons.log). Build time: 12 min 59 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 0 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/fixme_todo.log) |
| clang-tidy | :white_check_mark: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at 237cbe12bd0aeb4ec71c0fe644844712a5b5be4a after being merged into the base branch at 7ccf66c69acad0ca8cf8028260f65fe36eb5be20.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1166/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2022-02-17 23:15 UTC, merged

2022-02-18 00:02 UTC, kutschke commented
> I didn’t touch the script that makes those files, so I guess it’s historical and should probably be fixed at some point… Eric

I agree that this is outside the scope of this PR.  And the PR is merged.

Now that I have dredged up memories from the distant past, I think that this was done on purpose.  My instinct now is that we will never want non-trig builds in UPS.  @eflumerf and @rlcee do you agree?  If so, I will put in a PR to take out the ones we don't want.