Calo Photon Generator Edits
Mu2e/Offline pull request #758
Opened 2022-04-07 20:50 UTC by sophiemiddleton

Hope to address issues in: https://github.com/Mu2e/Offline/issues/755

2022-04-07 20:55 UTC, FNALbuild commented
Hi @sophiemiddleton,
You have proposed changes to files in these packages:
- EventGenerator

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for b97e79f5607b94ea4558e66f36df422620c4cf8d: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2022-04-07 21:19 UTC, FNALbuild commented
:sunny: The tests passed at b97e79f5607b94ea4558e66f36df422620c4cf8d.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged b97e79f5607b94ea4558e66f36df422620c4cf8d at 3f14c35cfb450dd297590592a927db663e4bcb01 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/scons.log). Build time: 10 min 43 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at b97e79f5607b94ea4558e66f36df422620c4cf8d after being merged into the base branch at 3f14c35cfb450dd297590592a927db663e4bcb01.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1242/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2022-04-08 04:31 UTC, kutschke commented
Thanks for making the requested changes - it's a big improvement.

When you are done with the work below, please remake the generator plot in Fig 2 of your writeup.  The jobs should be fast since you don't need to rerun G4.   No need to update the note - this is just to verify that we did not break something in the course of this work.

There are 4 outstanding issues and I will add @frankcporter and @bechenard as reviewers.   Please approve the PR when the issue I mention you in is resolved to your satisfaction.

1. This one is for Frank.  In the email thread that said that you were comfortable with the approximations.  I want to double check one of the approximations.  The choice of pipe 1 to 5 is made using only the radius of the large torus section not on the full length of each pipe; the generation point is then uniformly distributed throughout the pipe.  This under samples the inner pipes. These end effects are fairly large for the innermost pipe.  You have the information to do this correctly and you use it when choosing which of the 3 pipe sections to use.  Frank:  is this OK as is or should it be fixed?
2.  In the thread on PR #706, Dave said that you should not create the PrimaryParticle data product in this module.  You should created it later in your workflow using an appropriately configured instance of FindMCPrimary.  See https://github.com/Mu2e/Offline/pull/706#issuecomment-10904901423.   So please remove all references to that product.
3. Something has been bothering me since I started looking at this. Bertrand and I have talked about it.  The Jacobean to transform from (x,y,z) to your 3 spatial coordinates describing a torus is not 1.  In general you need to include the Jacobean somewhere in this generator.  However I think I know the answer.  It turns out that the expression for the volume of a torus is;  (2 pi R) * (pi r^2), where r is the pipe radius and R is the radius of the big circle through the center of the pipe.  So it's the same as the volume of a right circular cylinder with the same radius as the pipe and a length equal to the circumference of the centerline of the torus.  From this I conclude that there must be an exact cancelation of the effect of the Jacobean when you integrate a constant function over the volume of a torus.  The Jacobean would be important if the efficiency were a function of location within the torus or if you sampled over a subset of the volume.   I am confident enough in this that I am not asking for any more work on this but if anyone knows the answer with certainty I would appreciate hearing it.  Bertrand are you OK with this?
4. The last thing is another computing issue.  After you have chosen a pipe, you randomly chose a point in each of the 3 pipe sections and then pick a section.  It's better to pick a section first and then compute just one point. I would also encapsulate the calculation in a function - you only need two functions since you can use the same function for the two torus sections; the second function is for the straight section.  I recommend declaring the functions in an anonymous namespace within this file.

2022-04-08 04:36 UTC, FNALbuild commented
:memo: The HEAD of `main` has changed to a647ccc2b1ffa115208bc13741c3cf8cceb919cf. Tests are now out of date.

2022-04-08 12:30 UTC, bechenard commented
Hi Rob,

Regarding point 3, it's not really the Jacobian but the sampling 
distribution. For a cylinder, selecting a point uniformly in the 
cross-section disk is given by r*sqrt(random). I believe you have a 
non-trivial transformation as soon as the metric of your space isn't 
constant (i.e. a n-dimensional box), but I don't have any proof.

This said, it should be fine to generate the photons from the center of 
the torus. As I mentioned earlier, we just want to have a good idea of 
what the calibration spectrum will look like, but we won't need the MC 
to extract the calibration constant.

Cheers,

Bertrand

On 4/7/2022 9:32 PM, Rob Kutschke wrote:
>
> Thanks for making the requested changes - it's a big improvement.
>
> When you are done with the work below, please remake the generator 
> plot in Fig 2 of your writeup. The jobs should be fast since you don't 
> need to rerun G4. No need to update the note - this is just to verify 
> that we did not break something in the course of this work.
>
> There are 4 outstanding issues and I will add @frankcporter 
> <https://github.com/frankcporter> and @bechenard 
> <https://github.com/bechenard> as reviewers. Please approve the PR 
> when the issue I mention you in is resolved to your satisfaction.
>
>  1. This one is for Frank. In the email thread that said that you were
>     comfortable with the approximations. I want to double check one of
>     the approximations. The choice of pipe 1 to 5 is made using only
>     the radius of the large torus section not on the full length of
>     each pipe; the generation point is then uniformly distributed
>     throughout the pipe. This under samples the inner pipes. These end
>     effects are fairly large for the innermost pipe. You have the
>     information to do this correctly and you use it when choosing
>     which of the 3 pipe sections to use. Frank: is this OK as is or
>     should it be fixed?
>  2. In the thread on PR #706
>     <https://github.com/Mu2e/Offline/pull/706>, Dave said that you
>     should not create the PrimaryParticle data product in this module.
>     You should created it later in your workflow using an
>     appropriately configured instance of FindMCPrimary. See #706
>     (comment)
>     <https://github.com/Mu2e/Offline/pull/706#issuecomment-10904901423>.
>     So please remove all references to that product.
>  3. Something has been bothering me since I started looking at this.
>     Bertrand and I have talked about it. The Jacobean to transform
>     from (x,y,z) to your 3 spatial coordinates describing a torus is
>     not 1. In general you need to include the Jacobean somewhere in
>     this generator. However I think I know the answer. It turns out
>     that the expression for the volume of a torus is; (2 pi R) * (pi
>     r^2), where r is the pipe radius and R is the radius of the big
>     circle through the center of the pipe. So it's the same as the
>     volume of a right circular cylinder with the same radius as the
>     pipe and a length equal to the circumference of the centerline of
>     the torus. From this I conclude that there must be an exact
>     cancelation of the effect of the Jacobean when you integrate a
>     constant function over the volume of a torus. The Jacobean would
>     be important if the efficiency were a function of location within
>     the torus or if you sampled over a subset of the volume. I am
>     confident enough in this that I am not asking for any more work on
>     this but if anyone knows the answer with certainty I would
>     appreciate hearing it. Bertrand are you OK with this?
>  4. The last thing is another computing issue. After you have chosen a
>     pipe, you randomly chose a point in each of the 3 pipe sections
>     and then pick a section. It's better to pick a section first and
>     then compute just one point. I would also encapsulate the
>     calculation in a function - you only need two functions since you
>     can use the same function for the two torus sections; the second
>     function is for the straight section. I recommend declaring the
>     functions in an anonymous namespace within this file.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/758#issuecomment-1092431994>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JBISJTVN4WPCMOZVVLVD6ZERANCNFSM5S2SHD2Q>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2022-04-08 13:33 UTC, kutschke commented
> Hi Rob, Regarding point 3, it's not really the Jacobian but the sampling distribution. For a cylinder, selecting a point uniformly in the cross-section disk is given by r*sqrt(random). I believe you have a non-trivial transformation as soon as the metric of your space isn't constant (i.e. a n-dimensional box), but I don't have any proof. This said, it should be fine to generate the photons from the center of the torus. As I mentioned earlier, we just want to have a good idea of what the calibration spectrum will look like, but we won't need the MC to extract the calibration constant. Cheers, Bertrand
> […](#)

She fixed the code to correctly generate photons over a uniform disk.  We caught that early in the review and it is now R*sqrt(_randflat).  What I was not sure about is if that's the whole story.  Last night I thought there was a magical cancellation that saves us but this morning I think that's wrong.

Here is my current thought experiment.  Imagine a torus lying flat on a horizontal surface.  Make a vertical circular cut around the centerline to define  an inner section and an outer section.  I am pretty sure that the two sections have different volumes but that her algorithm will generate equal populations in the two sections.  Her 2D differential volume element should be  circular wedge, not a disk.  I have not yet figured out the mathematical form - that's connected to the Jacobian.

2022-04-08 15:22 UTC, sophiemiddleton commented
@kutschke, @dnbrow01 can you provide an example of your point in (2)? I already use FindMCPrimary in the FCL file, but the reco code will throw errors without a primary particle being created in the module, is there a way around?

2022-04-08 15:30 UTC, sophiemiddleton commented
@kutschke for point (4) you mean where I find the "sample" and then ask if x,y are within certain sections? But to get the information about those sections you have to do all the calculations preceding that "if(sample.....)elseif..." statement. The sections are not all the same size, so it would be complicated to select a section first, although I agree the way it seems weird. Did I misunderstand your comment?

2022-04-08 16:14 UTC, dnbrow01 commented
> @kutschke, @dnbrow01 can you provide an example of your point in (2)? I already use FindMCPrimary in the FCL file, but the reco code will throw errors without a primary particle being created in the module, is there a way around?

Sorry, I think you want @brownd1978 ?  re:  PR 758.

2022-04-08 16:36 UTC, frankcporter commented
Hi Rob –

I hope I am not missing the point.
Yes, approximating the torus as a cylinder is not quite right.
But in this case the cylinder is “long and thin”, so the approximation
being made should be rather good, and good enough for the purposes
we need it for. Am I missing something?

cheers,
frank

Frank Porter
Professor of Physics
Caltech
***@***.******@***.***>
(626) 395-6777

From: Rob Kutschke ***@***.***>
Sent: Friday, April 8, 2022 6:34 AM
To: Mu2e/Offline ***@***.***>
Cc: Porter, Frank C. ***@***.***>; Mention ***@***.***>
Subject: Re: [Mu2e/Offline] Calo Photon Generator Edits (PR #758)


Hi Rob, Regarding point 3, it's not really the Jacobian but the sampling distribution. For a cylinder, selecting a point uniformly in the cross-section disk is given by r*sqrt(random). I believe you have a non-trivial transformation as soon as the metric of your space isn't constant (i.e. a n-dimensional box), but I don't have any proof. This said, it should be fine to generate the photons from the center of the torus. As I mentioned earlier, we just want to have a good idea of what the calibration spectrum will look like, but we won't need the MC to extract the calibration constant. Cheers, Bertrand
…

She fixed the code to correctly generate photons over a uniform disk. We caught that early in the review and it is now R*sqrt(_randflat). What I was not sure about is if that's the whole story. Last night I thought there was a magical cancellation that saves us but this morning I think that's wrong.

Here is my current thought experiment. Imagine a torus lying flat on a horizontal surface. Make a vertical circular cut around the centerline to define an inner section and an outer section. I am pretty sure that the two sections have different volumes but that her algorithm will generate equal populations in the two sections. Her 2D differential volume element should be circular wedge, not a disk. I have not yet figured out the mathematical form - that's connected to the Jacobian.

—
Reply to this email directly, view it on GitHub<https://github.com/Mu2e/Offline/pull/758#issuecomment-1092866070>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABQOT5X2ZBV3PWTFTGG5ZILVEAYTVANCNFSM5S2SHD2Q>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-04-08 19:58 UTC, frankcporter commented
On this point:

  1.  This one is for Frank. In the email thread that said that you were comfortable with the approximations. I want to double check one of the approximations. The choice of pipe 1 to 5 is made using only the radius of the large torus section not on the full length of each pipe; the generation point is then uniformly distributed throughout the pipe. This under samples the inner pipes. These end effects are fairly large for the innermost pipe. You have the information to do this correctly and you use it when choosing which of the 3 pipe sections to use. Frank: is this OK as is or should it be fixed?
Thanks, Rob. Yes, I think this should be fixed. The longest pipes are actually the ones with the smallest radii, so it is even a (somewhat) bigger effect than at first sight. I would like to request:


  1.  Add to the documentation the manner of choosing the pipe (idx) [I had assumed it was just done randomly on the index, but Rob is correct that in the code it is based on the large bend radius].
  2.  Change the code (line 166 of EventGenerator/src/CaloCalibGun_module.cc) to base the idx selection on the total pipe length. An alternative, which is good to +- 5%, would be to select randomly on (1 to 5) [that is, as I had thought was being done].

cheers,
frank

2022-04-08 21:53 UTC, sophiemiddleton commented
thanks @frankcporter for spotting that. Yes, it should be a random pipe (I have changed it). I think at some point it was 1 - 5 i.e. pipe number and it got changed (I cant remember why).

2022-04-11 20:02 UTC, kutschke commented
> > @kutschke, @dnbrow01 can you provide an example of your point in (2)? I already use FindMCPrimary in the FCL file, but the reco code will throw errors without a primary particle being created in the module, is there a way around?
> 
> Sorry, I think you want @brownd1978 ? re: PR 758.

Sophie, please be more specific about what errors are thrown.

2022-04-11 21:03 UTC, kutschke commented
> @kutschke for point (4) you mean where I find the "sample" and then ask if x,y are within certain sections? But to get the information about those sections you have to do all the calculations preceding that "if(sample.....)elseif..." statement. The sections are not all the same size, so it would be complicated to select a section first, although I agree the way it seems weird. Did I misunderstand your comment?

In order to pick a section, you only need to compute, three things: circLgTor + circSmTor + lenStrait and then choose the random number named sample.  None of these 3 quantities depend on the random numbers drawn to compute the positions in the 3 sections - they are static properties of the geometry.  In fact you can move most of this computation to beginRun and you should.

2022-04-11 21:14 UTC, kutschke commented
Thanks for updating the way that you choose the pipe.  I have several followup comments.

1. Ideally you would generate decays uniformly throughout the volume of the pipes; you make two approximations that deviate from this.   Please document these approximations as comments at the top of the code.  One is that you treat all 5 pipes as equal volume when you pick a pipe.  The second is that you treat each torus is if it were a right circular cylinder with a length equal to the arc length of the centerline of the torus.  I am OK with these approximations but be clear that you are making them - otherwise the code just looks wrong.
2. At the line: https://github.com/sophiemiddleton/Offline/blob/c3ca78a1eaf64607c06fe9d3dbdb22aca08bd383/EventGenerator/src/CaloCalibGun_module.cc#L132  That comment was  and is wrong.  Also the next 3 lines are no longer needed.   Remove all 4 lines and remove the declaration of _randomRad in the header.
3. At line https://github.com/sophiemiddleton/Offline/blob/c3ca78a1eaf64607c06fe9d3dbdb22aca08bd383/EventGenerator/src/CaloCalibGun_module.cc#L168  Use _randFlat not rand.  We require that all random engines be managed by the RandomNumberService with seeds managed by SeedService.  This is to ensure that we can control the uniqueness and repeatability of how random variates are chosen.  You will need to update the algorithm since the range of values returned by rand and _randFlat are different.

2022-04-12 15:19 UTC, kutschke commented
> I will be on vacation from tomorrow for a week. I will try to get to this today, but it may not be done til after my vacation

Ok.  I will watch for it either way.  Enjoy your vacation.

2022-04-22 14:50 UTC, sophiemiddleton commented
@kutschke I have completeed 1 and 2 of your additional comments, can you advise how to get a random number of 1-5 from randFlat. Is it not just 0 or 1?

2022-04-22 16:00 UTC, kutschke commented
> @kutschke I have completeed 1 and 2 of your additional comments, can you advise how to get a random number of 1-5 from randFlat. Is it not just 0 or 1?

This will give 0 to 4:
`int i = std::round( 5.*flat1_.fire());`

And this will give 1 to 5:
`int i = std::round( 5.*flat1_.fire())+1;`

I believe that RandFlat returns values on the semi-open interval [0,1).  So you will never get 5 in the first case or 6 in the second.

2022-04-22 16:01 UTC, bechenard commented
Hi Sophie,

Something like "int(5*random.flat())+1" should do the trick.

Bertrand

On 4/22/2022 7:51 AM, Sophie Middleton wrote:
>
> @kutschke <https://github.com/kutschke> I have completeed 1 and 2 of 
> your additional comments, can you advise how to get a random number of 
> 1-5 from randFlat. Is it not just 0 or 1?
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/758#issuecomment-1106593015>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JAFXQ4OKR6S3WR56KTVGK4FVANCNFSM5S2SHD2Q>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2022-04-22 16:02 UTC, sophiemiddleton commented
OK, thanks for the advice, I'll try that

2022-04-22 16:03 UTC, kutschke commented
OOps - blundered by comment.  Editted it together it right.

2022-04-22 16:03 UTC, bechenard commented
I think we just crossed emails. On a purely mathematical (and pedantic 
note), the end of the interval has measure null, so it doesn't rally 
matter if it is open or closed. Ok, I shut up...

On 4/22/2022 9:00 AM, Rob Kutschke wrote:
>
>     @kutschke <https://github.com/kutschke> I have completeed 1 and 2
>     of your additional comments, can you advise how to get a random
>     number of 1-5 from randFlat. Is it not just 0 or 1?
>
> This will give 0 to 4:
> |int i = std::round( 5.*flat1_.fire());|
>
> And this will give 1 to 5:
> |int i = std::round( 5.*flat1_.fire())+1;|
>
> I believe that RandFlat returns values on the semi-open interval 
> [0,1). So you will never get 5 in the first case or 6 in the second.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/758#issuecomment-1106652402>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JCGGFN3OYQO6K7DGA3VGLEKTANCNFSM5S2SHD2Q>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2022-04-22 16:05 UTC, kutschke commented
> I think we just crossed emails. On a purely mathematical (and pedantic note), the end of the interval has measure null, so it doesn't rally matter if it is open or closed. Ok, I shut up...

Your answer was might and mine was wrong - int not round, is right.

2022-04-22 16:22 UTC, sophiemiddleton commented
Ok, I made the changes and checked it still works

2022-04-22 16:25 UTC, kutschke requested changes

2022-04-22 16:25 UTC, kutschke commented on EventGenerator/src/CaloCalibGun_module.cc
> +    unsigned int idx = int(5*_randFlat.fire())+1;
Don't you want an index in the range 0 to 4, not 1 to 5?  You are indexing into std::vector with dimension 5.

2022-04-22 16:26 UTC, frankcporter commented
Just to remark that you are using the wrong measure on
the (discrete, finite) set of computer numbers – the end of an interval
is not of measure zero, so if the interval is closed, the probability
is not zero to sample the end.

cheers,
frank

Frank Porter
Professor of Physics
Caltech
***@***.******@***.***>
(626) 395-6777

From: Bertrand Echenard ***@***.***>
Sent: Friday, April 22, 2022 9:03 AM
To: Mu2e/Offline ***@***.***>
Cc: Porter, Frank C. ***@***.***>; Mention ***@***.***>
Subject: Re: [Mu2e/Offline] Calo Photon Generator Edits (PR #758)

I think we just crossed emails. On a purely mathematical (and pedantic
note), the end of the interval has measure null, so it doesn't rally
matter if it is open or closed. Ok, I shut up...

On 4/22/2022 9:00 AM, Rob Kutschke wrote:
>
> @kutschke <https://github.com/kutschke> I have completeed 1 and 2
> of your additional comments, can you advise how to get a random
> number of 1-5 from randFlat. Is it not just 0 or 1?
>
> This will give 0 to 4:
> |int i = std::round( 5.*flat1_.fire());|
>
> And this will give 1 to 5:
> |int i = std::round( 5.*flat1_.fire())+1;|
>
> I believe that RandFlat returns values on the semi-open interval
> [0,1). So you will never get 5 in the first case or 6 in the second.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mu2e/Offline/pull/758#issuecomment-1106652402>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJ27JCGGFN3OYQO6K7DGA3VGLEKTANCNFSM5S2SHD2Q>.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***<mailto:***@***.***>>
>

—
Reply to this email directly, view it on GitHub<https://github.com/Mu2e/Offline/pull/758#issuecomment-1106654467>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABQOT5VBXNISOBYW237PYILVGLEUFANCNFSM5S2SHD2Q>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-04-22 16:27 UTC, bechenard commented
Correct, I forgot the discretness of the computer numbers....

On 4/22/2022 9:26 AM, frankcporter wrote:
> Just to remark that you are using the wrong measure on
> the (discrete, finite) set of computer numbers – the end of an interval
> is not of measure zero, so if the interval is closed, the probability
> is not zero to sample the end.
>
> cheers,
> frank
>
> Frank Porter
> Professor of Physics
> Caltech
> ***@***.******@***.***>
> (626) 395-6777
>
> From: Bertrand Echenard ***@***.***>
> Sent: Friday, April 22, 2022 9:03 AM
> To: Mu2e/Offline ***@***.***>
> Cc: Porter, Frank C. ***@***.***>; Mention ***@***.***>
> Subject: Re: [Mu2e/Offline] Calo Photon Generator Edits (PR #758)
>
> I think we just crossed emails. On a purely mathematical (and pedantic
> note), the end of the interval has measure null, so it doesn't rally
> matter if it is open or closed. Ok, I shut up...
>
> On 4/22/2022 9:00 AM, Rob Kutschke wrote:
> >
> > @kutschke <https://github.com/kutschke> I have completeed 1 and 2
> > of your additional comments, can you advise how to get a random
> > number of 1-5 from randFlat. Is it not just 0 or 1?
> >
> > This will give 0 to 4:
> > |int i = std::round( 5.*flat1_.fire());|
> >
> > And this will give 1 to 5:
> > |int i = std::round( 5.*flat1_.fire())+1;|
> >
> > I believe that RandFlat returns values on the semi-open interval
> > [0,1). So you will never get 5 in the first case or 6 in the second.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Mu2e/Offline/pull/758#issuecomment-1106652402>, or
> > unsubscribe
> > 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JCGGFN3OYQO6K7DGA3VGLEKTANCNFSM5S2SHD2Q>.
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***<mailto:***@***.***>>
> >
>
> —
> Reply to this email directly, view it on 
> GitHub<https://github.com/Mu2e/Offline/pull/758#issuecomment-1106654467>, 
> or 
> unsubscribe<https://github.com/notifications/unsubscribe-auth/ABQOT5VBXNISOBYW237PYILVGLEUFANCNFSM5S2SHD2Q>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.******@***.***>>
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/758#issuecomment-1106673699>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JBDCNJDDFYBDEOEOU3VGLHMLANCNFSM5S2SHD2Q>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2022-04-22 16:56 UTC, sophiemiddleton commented
Sorry, I edited the code to check and forgot to change back (Rob is right it should be 0 - 4, that is what I had checked and it worked)

2022-04-22 17:36 UTC, gaponenko commented
On Fri, 22 Apr 2022, Bertrand Echenard wrote:

> I think we just crossed emails. On a purely mathematical (and pedantic 
> note), the end of the interval has measure null, so it doesn't rally 
> matter if it is open or closed. 

Yes.  On the other hand on a real computer with a finite number of bits 
used to represent a floating point number there is a finite probability
to get a sample exactly at the end of an interval unless it is excluded
by the API.

Andrei

2022-04-22 17:38 UTC, bechenard commented
Yes, Frank already made that comment. I adopted a theorist point of 
view, glossing over the limitations of this finite world!

On 4/22/2022 10:37 AM, Andrei Gaponenko wrote:
>
>
> On Fri, 22 Apr 2022, Bertrand Echenard wrote:
>
> > I think we just crossed emails. On a purely mathematical (and pedantic
> > note), the end of the interval has measure null, so it doesn't rally
> > matter if it is open or closed.
>
> Yes. On the other hand on a real computer with a finite number of bits
> used to represent a floating point number there is a finite probability
> to get a sample exactly at the end of an interval unless it is excluded
> by the API.
>
> Andrei
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/Mu2e/Offline/pull/758#issuecomment-1106723817>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABJ27JH3KYIE6C7FZTYZADLVGLPT5ANCNFSM5S2SHD2Q>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2022-04-22 19:14 UTC, kutschke commented
@FNALbuild run build test

2022-04-22 19:15 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for deee43e9cc278f110e30797aa8947672136a9452: build  (Build queue is empty)

2022-04-22 19:28 UTC, kutschke commented on EventGenerator/src/CaloCalibGun_module.cc
> +    unsigned int idx = int(5*_randFlat.fire())+1;
Thanks for fixing this.

2022-04-22 19:40 UTC, FNALbuild commented
:sunny: The build tests passed at deee43e9cc278f110e30797aa8947672136a9452.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged deee43e9cc278f110e30797aa8947672136a9452 at c4038a072f9cc68dbc79890808f55c4b34a3bc0a |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/scons.log). Build time: 11 min 23 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at deee43e9cc278f110e30797aa8947672136a9452 after being merged into the base branch at c4038a072f9cc68dbc79890808f55c4b34a3bc0a.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1268/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2022-04-22 19:51 UTC, kutschke approved these changes

2022-04-22 19:51 UTC, merged