Strawstatus
Mu2e/Offline pull request #767
Opened 2022-04-15 23:14 UTC by brownd1978

Allow better transfer of StrawStatus into StrawHitFlag and use of that in downstream reconstruction.  Also fixed some whitespace.

2022-04-15 23:19 UTC, FNALbuild commented
Hi @brownd1978,
You have proposed changes to files in these packages:
- Filters
- DataProducts
- RecoDataProducts
- CommonMC
- TrackerConditions
- TrkHitReco
- TrkPatRec
- CalPatRec

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 697e51e8c9896e0eb67f10ff6ee1a0fa6a4e933d: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2022-04-15 23:45 UTC, FNALbuild commented
:sunny: The tests passed at 697e51e8c9896e0eb67f10ff6ee1a0fa6a4e933d.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged 697e51e8c9896e0eb67f10ff6ee1a0fa6a4e933d at b8384d9a90fb0c536bec4fd13a542426c7df423e |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/scons.log). Build time: 12 min 28 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :wavy_dash: | [TODO (1) FIXME (4) in 9 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at 697e51e8c9896e0eb67f10ff6ee1a0fa6a4e933d after being merged into the base branch at b8384d9a90fb0c536bec4fd13a542426c7df423e.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1253/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2022-04-19 03:51 UTC, bonventre requested changes

2022-04-19 03:54 UTC, brownd1978 commented on TrkHitReco/src/StrawHitRecoUtils.cc
> +    } else if ( trackerStatus.suppress(sid)) {
I think its right.  noSignal corresponds to noHV, noGas, noElectronics, ... and suppress we agreed means those signals should never be used.  But there is something funny with the logic: the else if can never be triggered.  Let me look it over.

2022-04-19 03:57 UTC, brownd1978 commented on TrkHitReco/src/StrawHitRecoUtils.cc
> +    } else if ( trackerStatus.suppress(sid)) {
Yes you're right, the _function_ should be noisy.

2022-04-19 06:15 UTC, bonventre approved these changes

2022-04-19 16:24 UTC, kutschke commented
@FNALbuild run build test

2022-04-19 16:29 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for f1a2c9733646fc8f6bef6994c09b3f87189cbe41: build  (Build queue is empty)

2022-04-19 16:55 UTC, FNALbuild commented
:sunny: The tests passed at f1a2c9733646fc8f6bef6994c09b3f87189cbe41.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| merge | :white_check_mark: | Merged f1a2c9733646fc8f6bef6994c09b3f87189cbe41 at 37fe63688b2d42e1107e1eac3799656b02dab2f1 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/scons.log). Build time: 11 min 55 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :wavy_dash: | [TODO (1) FIXME (4) in 8 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/artifact/clang-tidy.log) |


N.B. These results were obtained from a build of this Pull Request at f1a2c9733646fc8f6bef6994c09b3f87189cbe41 after being merged into the base branch at 37fe63688b2d42e1107e1eac3799656b02dab2f1.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1260/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2022-04-19 16:57 UTC, merged