Added new variables to BkgDiag
Mu2e/Offline pull request #961
Opened 2023-03-13 22:35 UTC by myucel-fnal

2023-03-13 22:36 UTC, FNALbuild commented
Hi @myucel-fnal,
You have proposed changes to files in these packages:
- TrkDiag

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).



:memo: The author of this pull request is not a member of the [Mu2e github organisation](https://github.com/Mu2e).



[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2023-03-14 20:44 UTC, brownd1978 commented on TrkDiag/src/BkgDiag_module.cc
> +        sumEdep +=  ch.energyDep();
edep is measured per straw.  I think this sum should be weighted by the # of straw hits (ch.nStrawHits()

2023-03-14 20:44 UTC, brownd1978 commented on TrkDiag/src/BkgDiag_module.cc
> +        sqrSumDeltaX += std::pow(ch.pos().X() - _cpos.X(),2);
The RMS calculation is mathematically correct, but I suspect we will have better discrimination computing the rms of the transverse distance to the straw, not the hit.  That will remove the uncertainty from the position along the straw, and it automatically combines the 2 dimensions.  You can compute that using 2 line POCA, one line being in Z through the cluster position, the other being along the straw (udir) through the hit position.  Or its simple enough to compute analytically.

2023-03-16 23:15 UTC, brownd1978 commented
@FNALbuild run build test

2023-03-16 23:16 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for b46333a79c6b464466f8190ced5b9f068178501f: build  (Build queue is empty)

2023-03-16 23:32 UTC, FNALbuild commented
:umbrella: The build is failing at b46333a79c6b464466f8190ced5b9f068178501f.

```
Selected class -> art::Wrapper<std::vectoscons: *** [build/sl7-prof-e20-p039/Offline/tmp/TrkDiag/src/BkgDiag_module.os] Error 1
```


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged b46333a79c6b464466f8190ced5b9f068178501f at 5315fd2d3d8bc8ac4c4891d2a25eb547d84170a2 |
| build (prof) | :x: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/scons.log).  |
| ceSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/ceSimReco.log)  |
| g4test_03MT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/g4test_03MT.log)  |
| transportOnly | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/transportOnly.log)  |
| POT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/POT.log)  |
| g4study | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/g4study.log)  |
| cosmicSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/cosmicOffSpill.log)  |
| ceSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/ceSteps.log)  |
| ceDigi | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/ceDigi.log)  |
| muDauSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/muDauSteps.log)  |
| ceMix | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/ceMix.log)  |
| rootOverlaps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at b46333a79c6b464466f8190ced5b9f068178501f after being merged into the base branch at 5315fd2d3d8bc8ac4c4891d2a25eb547d84170a2.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1604/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2023-03-17 03:09 UTC, kutschke requested changes

2023-03-17 03:09 UTC, kutschke commented on TrkDiag/src/BkgDiag_module.cc
> +      _rmscposx = sdt::sqrt(sqrSumDeltaX/_nchits);
This line is the build error sdt --> std

2023-03-20 18:44 UTC, kutschke commented
@myucel-fnal I am checking in.  I think that I am waiting for you to make a commit to fix the build issue and push it to your fork.  Are we on the same page?

2023-03-20 21:31 UTC, kutschke commented
@FNALbuild run build test

2023-03-20 21:32 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 4dd828007ca52ffb5c1c68ec1731818b621b9710: build  (Build queue has 2 jobs)

2023-03-20 21:57 UTC, FNALbuild commented
:sunny: The build tests passed at 4dd828007ca52ffb5c1c68ec1731818b621b9710.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 4dd828007ca52ffb5c1c68ec1731818b621b9710 at 5315fd2d3d8bc8ac4c4891d2a25eb547d84170a2 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/scons.log). Build time: 15 min 09 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :white_check_mark: | [TODO (0) FIXME (0) in 1 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 4dd828007ca52ffb5c1c68ec1731818b621b9710 after being merged into the base branch at 5315fd2d3d8bc8ac4c4891d2a25eb547d84170a2.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1605/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2023-03-20 22:00 UTC, kutschke approved these changes

2023-03-20 22:02 UTC, kutschke commented
The CI tests passed.

Dave made a suggestion about using a 2 line POCA - it was just a suggestion not a requirement.  Do you plan to incorporate that in this PR - if not then this PR is ready to merge.  Please let me know your plans.

2023-03-21 14:57 UTC, myucel-fnal commented
Let me work on those changes, I need to check results to make sure. Hopefully I am finished with it today.

2023-03-30 22:27 UTC, merged