SOFIE + Keras TF for FlagBkgHits using Stereo Hits
Mu2e/Offline pull request #977
Opened 2023-05-04 19:22 UTC by myucel-fnal

2023-05-04 19:23 UTC, FNALbuild commented
Hi @myucel-fnal,
You have proposed changes to files in these packages:
- TrkHitReco
- TrkDiag
- RecoDataProducts
- Mu2eKinKal

which require these tests: build.

@Mu2e/fnalbuild-users, @Mu2e/write have access to CI actions on [main](/Mu2e/Offline/tree/main).





:hourglass: The following tests have been triggered for 2c9eae3713795ab94bb26c6aa1783acade5eac8b: build  (Build queue is empty)


[About FNALbuild.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild) [Code review on Mu2e/Offline.](https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#Code_Review)

2023-05-04 19:23 UTC, FNALbuild commented
:bangbang: It was not possible to prepare the workspace for this test. This is often caused by merge conflicts - please check and try again.
```
> git diff --check | grep -i conflict
TrkHitReco/src/MakeStereoHits_module.cc:256: leftover conflict marker
TrkHitReco/src/MakeStereoHits_module.cc:261: leftover conflict marker
TrkHitReco/src/MakeStereoHits_module.cc:264: leftover conflict marker
```

| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :x: | 2c9eae3713795ab94bb26c6aa1783acade5eac8b into e580d26a54f1724f2bfc127c6b6bac1375fc880d merge failed |

2023-05-07 20:37 UTC, kutschke commented
@FNALbuild run build test

2023-05-07 20:38 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 252e02368e0c1007f0bc4cfcbc278b9dbf2d4f12: build  (Build queue is empty)

2023-05-07 20:51 UTC, FNALbuild commented
:umbrella: The build is failing at 252e02368e0c1007f0bc4cfcbc278b9dbf2d4f12.

```
scons: *** [build/sl7-prof-e20-p040/Offline/tmp/Mu2eKinKal/src/BkgANNSHU.os] Error 1
```


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 252e02368e0c1007f0bc4cfcbc278b9dbf2d4f12 at ff1ce98f48eb28f500f4e37a4e82ad430c24cdc4 |
| build (prof) | :x: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/scons.log).  |
| ceSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/ceSimReco.log)  |
| g4test_03MT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/g4test_03MT.log)  |
| transportOnly | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/transportOnly.log)  |
| POT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/POT.log)  |
| g4study | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/g4study.log)  |
| cosmicSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/cosmicOffSpill.log)  |
| ceSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/ceSteps.log)  |
| ceDigi | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/ceDigi.log)  |
| muDauSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/muDauSteps.log)  |
| ceMix | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/ceMix.log)  |
| rootOverlaps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :large_orange_diamond: | [TODO (2) FIXME (1) in 6 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 252e02368e0c1007f0bc4cfcbc278b9dbf2d4f12 after being merged into the base branch at ff1ce98f48eb28f500f4e37a4e82ad430c24cdc4.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1643/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2023-05-16 18:06 UTC, brownd1978 commented
@FNALbuild run build test

2023-05-16 18:06 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 2c2ac2557fa9de72d8e428300dd96d2ad99c1767: build  (Build queue is empty)

2023-05-16 18:22 UTC, FNALbuild commented
:umbrella: The build is failing at 2c2ac2557fa9de72d8e428300dd96d2ad99c1767.

```
scons: *** [build/sl7-prof-e20-p040/Offline/tmp/Mu2eKinKal/src/BkgANNSHU.os] Error 1
```


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 2c2ac2557fa9de72d8e428300dd96d2ad99c1767 at 412ec77161c853cc7b11dd63e526258d046f1ab7 |
| build (prof) | :x: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/scons.log).  |
| ceSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/ceSimReco.log)  |
| g4test_03MT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/g4test_03MT.log)  |
| transportOnly | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/transportOnly.log)  |
| POT | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/POT.log)  |
| g4study | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/g4study.log)  |
| cosmicSimReco | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/cosmicOffSpill.log)  |
| ceSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/ceSteps.log)  |
| ceDigi | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/ceDigi.log)  |
| muDauSteps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/muDauSteps.log)  |
| ceMix | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/ceMix.log)  |
| rootOverlaps | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :wavy_dash: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :large_orange_diamond: | [TODO (2) FIXME (1) in 6 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 2c2ac2557fa9de72d8e428300dd96d2ad99c1767 after being merged into the base branch at 412ec77161c853cc7b11dd63e526258d046f1ab7.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1648/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2023-05-16 18:41 UTC, brownd1978 commented
@FNALbuild run build test

2023-05-16 18:41 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 141c9e13348e4617c17390fdf80205b44e60545d: build  (Build queue is empty)

2023-05-16 19:04 UTC, FNALbuild commented
:sunny: The build tests passed at 141c9e13348e4617c17390fdf80205b44e60545d.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 141c9e13348e4617c17390fdf80205b44e60545d at 412ec77161c853cc7b11dd63e526258d046f1ab7 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/scons.log). Build time: 12 min 15 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :large_orange_diamond: | [TODO (2) FIXME (1) in 4 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 141c9e13348e4617c17390fdf80205b44e60545d after being merged into the base branch at 412ec77161c853cc7b11dd63e526258d046f1ab7.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1649/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2023-05-16 19:11 UTC, brownd1978 requested changes
Just a few small things to fix

2023-05-16 19:11 UTC, brownd1978 commented on RecoDataProducts/src/ComboHit.cc
> +              if(pshids.size() == 8) shids[ich].insert(shids[ich].end(),pshids[iph].begin(),pshids[iph].end());
This effectively turns off filling these indices, as the # of hits is never(?) 8.   I suspect the real problem is how these indices are being interpreted in FlagBkgHits.  I suggest to revert this change and create an issue, specific to stereo hits.

2023-05-16 19:11 UTC, brownd1978 commented on TrkDiag/fcl/prolog.fcl
> +  # BkgQualCollection:"FlagBkgHits"
please remove the commented line, git history will keep track of this change

2023-05-16 19:11 UTC, brownd1978 commented on TrkDiag/src/BkgDiag_module.cc
> +        if(ch.pos().Z() < zmin) zmin = ch.pos().Z();
zmin and zmax seem irrelevant now you have a sorted vector to fill _zmin and _zmax

2023-05-16 19:58 UTC, brownd1978 commented
@FNALbuild run build test

2023-05-16 19:58 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 865a17245fe5fc3dc7576591880ba8ba73263220: build  (Build queue is empty)

2023-05-16 20:09 UTC, brownd1978 reviewed
Another small issue

2023-05-16 20:31 UTC, FNALbuild commented
:sunny: The build tests passed at 865a17245fe5fc3dc7576591880ba8ba73263220.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 865a17245fe5fc3dc7576591880ba8ba73263220 at 412ec77161c853cc7b11dd63e526258d046f1ab7 |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/scons.log). Build time: 20 min 49 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :large_orange_diamond: | [TODO (2) FIXME (1) in 4 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [0 errors 0 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 865a17245fe5fc3dc7576591880ba8ba73263220 after being merged into the base branch at 412ec77161c853cc7b11dd63e526258d046f1ab7.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1650/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2023-05-17 03:49 UTC, myucel-fnal commented on TrkHitReco/src/FlagBkgHits_module.cc
> +      kerasvars.at(0) = sqrtf(cluster.pos().perp2());
Did that, plus changed std::vector to std::array. Due to std::array being created on stack it is supposed to be faster.

2023-05-17 21:28 UTC, brownd1978 commented on TrkHitReco/src/FlagBkgHits_module.cc
> +      kerasvars[0] = sqrtf(cluster.pos().perp2());
This is the same as cluster.pos.Rho()

2023-05-18 20:53 UTC, myucel-fnal commented on TrkHitReco/src/FlagBkgHits_module.cc
> +      kerasvars[0] = sqrtf(cluster.pos().perp2());
yes, do you want me to change it?

2023-05-24 16:09 UTC, kutschke commented
@FNALbuild run build test

2023-05-24 16:10 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for 197ea1875d219d514e48d67b4e1fbb75182de92c: build  (Build queue has 1 jobs)

2023-05-24 16:44 UTC, FNALbuild commented
:sunny: The build tests passed at 197ea1875d219d514e48d67b4e1fbb75182de92c.


| Test          | Result        | Details |
| ------------- |:-------------:| ------- |
| test with | :white_check_mark: | Command did not list any other PRs to include |
| merge | :white_check_mark: | Merged 197ea1875d219d514e48d67b4e1fbb75182de92c at 4adf099f6f2943ef431791e2018ed96b70e8e92a |
| build (prof) | :white_check_mark: | [Log file](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/scons.log). Build time: 21 min 56 sec |
| ceSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/ceSimReco.log)  |
| g4test_03MT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/g4test_03MT.log)  |
| transportOnly | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/transportOnly.log)  |
| POT | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/POT.log)  |
| g4study | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/g4study.log)  |
| cosmicSimReco | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/cosmicSimReco.log)  |
| cosmicOffSpill | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/cosmicOffSpill.log)  |
| ceSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/ceSteps.log)  |
| ceDigi | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/ceDigi.log)  |
| muDauSteps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/muDauSteps.log)  |
| ceMix | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/ceMix.log)  |
| rootOverlaps | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/rootOverlaps.log)  |
| g4surfaceCheck | :white_check_mark: | [Log file.](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/g4surfaceCheck.log)  |
| FIXME, TODO | :large_orange_diamond: | [TODO (2) FIXME (1) in 4 files](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/fixme_todo.log) |
| clang-tidy | :wavy_dash: | [12 errors 141 warnings](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/clang-tidy.log) |
| whitespace check | :white_check_mark: | [no whitespace errors found](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/artifact/whitespace_errs.log) |


N.B. These results were obtained from a build of this Pull Request at 197ea1875d219d514e48d67b4e1fbb75182de92c after being merged into the base branch at 4adf099f6f2943ef431791e2018ed96b70e8e92a.


For more information, please check the job page [here](https://buildmaster.fnal.gov/buildmaster/job/GitHubPRTests/job/mu2e-offline-build-test//1655/console).
Build artifacts are deleted after 5 days. If this is not desired, select `Keep this build forever` on the job page.

2023-05-24 21:50 UTC, FNALbuild commented
:memo: The HEAD of `main` has changed to 62fcecfefbce061eb045754c6b478e8971e8f548. Tests are now out of date.

2023-06-21 15:25 UTC, FNALbuild commented
:hourglass: The following tests have been triggered for b40750ea886563099cfa78b9243e1dd6858e9c3b: build  (Build queue is empty)

2023-06-22 18:42 UTC, merged